################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CC_DEPS := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Drivers/BSP/Components/ft5336 \
Drivers/BSP/STM32746G-Discovery \
Drivers/STM32F7xx_HAL_Driver/Src \
Middlewares/ST/TouchGFX/touchgfx/framework/source/platform/driver/touch \
Middlewares/ST/TouchGFX/touchgfx/framework/source/touchgfx/containers \
Middlewares/ST/TouchGFX/touchgfx/framework/source/touchgfx/containers/clock \
Middlewares/ST/TouchGFX/touchgfx/framework/source/touchgfx/containers/progress_indicators \
Middlewares/ST/TouchGFX/touchgfx/framework/source/touchgfx/containers/scrollers \
Middlewares/ST/TouchGFX/touchgfx/framework/source/touchgfx/widgets \
Middlewares/ST/TouchGFX/touchgfx/framework/source/touchgfx/widgets/canvas \
Middlewares/ST/TouchGFX/touchgfx/os \
Middlewares/Third_Party/FatFs/src \
Middlewares/Third_Party/FatFs/src/option \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
Middlewares/Third_Party/FreeRTOS/Source \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \
Middlewares/Third_Party/LwIP/src/api \
Middlewares/Third_Party/LwIP/src/apps/mqtt \
Middlewares/Third_Party/LwIP/src/core \
Middlewares/Third_Party/LwIP/src/core/ipv4 \
Middlewares/Third_Party/LwIP/src/core/ipv6 \
Middlewares/Third_Party/LwIP/src/netif \
Middlewares/Third_Party/LwIP/src/netif/ppp \
Middlewares/Third_Party/LwIP/system/OS \
Middlewares/Third_Party/mbedTLS/library \
Src \
Startup \
TouchGFX/build/MINGW32_NT-6.2/generated/fonts/src \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/common \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/iocontrol_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/logger_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/main_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/network_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/images/src \
TouchGFX/build/MINGW32_NT-6.2/generated/images/src/__designer \
TouchGFX/build/MINGW32_NT-6.2/generated/texts/src \
TouchGFX/build/MINGW32_NT-6.2/gui/src/common \
TouchGFX/build/MINGW32_NT-6.2/gui/src/iocontrol_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/logger_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/main_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/model \
TouchGFX/build/MINGW32_NT-6.2/gui/src/network_screen \
TouchGFX/build/MINGW32_NT-6.2/simulator \
TouchGFX/build/MINGW32_NT-6.2/touchgfx/framework/source/platform/driver/touch \
TouchGFX/build/MINGW32_NT-6.2/touchgfx/framework/source/platform/hal/simulator/sdl2 \
TouchGFX/build/STM32F746-DISCO/Core/Src \
TouchGFX/build/STM32F746-DISCO/Drivers/BSP/Components/ft5336 \
TouchGFX/build/STM32F746-DISCO/Drivers/BSP/STM32746G-Discovery \
TouchGFX/build/STM32F746-DISCO/Drivers/CMSIS/Device/ST/STM32F7xx/Source/Templates/gcc \
TouchGFX/build/STM32F746-DISCO/Drivers/STM32F7xx_HAL_Driver/Src \
TouchGFX/build/STM32F746-DISCO/FATFS/App \
TouchGFX/build/STM32F746-DISCO/FATFS/Target \
TouchGFX/build/STM32F746-DISCO/JSMN/src \
TouchGFX/build/STM32F746-DISCO/LWHTTP/src \
TouchGFX/build/STM32F746-DISCO/LWIP/App \
TouchGFX/build/STM32F746-DISCO/LWIP/Target \
TouchGFX/build/STM32F746-DISCO/Middlewares/Third_Party/FatFs/src \
TouchGFX/build/STM32F746-DISCO/Middlewares/Third_Party/FatFs/src/option \
TouchGFX/build/STM32F746-DISCO/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
TouchGFX/build/STM32F746-DISCO/Middlewares/Third_Party/FreeRTOS/Source \
TouchGFX/build/STM32F746-DISCO/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 \
TouchGFX/build/STM32F746-DISCO/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \
TouchGFX/build/STM32F746-DISCO/Middlewares/Third_Party/LwIP/src/api \
TouchGFX/build/STM32F746-DISCO/Middlewares/Third_Party/LwIP/src/apps/mqtt \
TouchGFX/build/STM32F746-DISCO/Middlewares/Third_Party/LwIP/src/core \
TouchGFX/build/STM32F746-DISCO/Middlewares/Third_Party/LwIP/src/core/ipv4 \
TouchGFX/build/STM32F746-DISCO/Middlewares/Third_Party/LwIP/src/core/ipv6 \
TouchGFX/build/STM32F746-DISCO/Middlewares/Third_Party/LwIP/src/netif \
TouchGFX/build/STM32F746-DISCO/Middlewares/Third_Party/LwIP/src/netif/ppp \
TouchGFX/build/STM32F746-DISCO/Middlewares/Third_Party/LwIP/system/OS \
TouchGFX/build/STM32F746-DISCO/SDLOG/src \
TouchGFX/build/STM32F746-DISCO/TouchGFX/generated/fonts/src \
TouchGFX/build/STM32F746-DISCO/TouchGFX/generated/gui_generated/src/common \
TouchGFX/build/STM32F746-DISCO/TouchGFX/generated/gui_generated/src/iocontrol_screen \
TouchGFX/build/STM32F746-DISCO/TouchGFX/generated/gui_generated/src/logger_screen \
TouchGFX/build/STM32F746-DISCO/TouchGFX/generated/gui_generated/src/main_screen \
TouchGFX/build/STM32F746-DISCO/TouchGFX/generated/gui_generated/src/network_screen \
TouchGFX/build/STM32F746-DISCO/TouchGFX/generated/images/src \
TouchGFX/build/STM32F746-DISCO/TouchGFX/generated/images/src/__designer \
TouchGFX/build/STM32F746-DISCO/TouchGFX/generated/texts/src \
TouchGFX/build/STM32F746-DISCO/TouchGFX/gui/src/common \
TouchGFX/build/STM32F746-DISCO/TouchGFX/gui/src/iocontrol_screen \
TouchGFX/build/STM32F746-DISCO/TouchGFX/gui/src/logger_screen \
TouchGFX/build/STM32F746-DISCO/TouchGFX/gui/src/main_screen \
TouchGFX/build/STM32F746-DISCO/TouchGFX/gui/src/model \
TouchGFX/build/STM32F746-DISCO/TouchGFX/gui/src/network_screen \
TouchGFX/build/STM32F746-DISCO/TouchGFX/os \
TouchGFX/build/STM32F746-DISCO/TouchGFX/target \
TouchGFX/build/bin \
TouchGFX/generated/fonts/src \
TouchGFX/generated/gui_generated/src/common \
TouchGFX/generated/gui_generated/src/iocontrol_screen \
TouchGFX/generated/gui_generated/src/logger_screen \
TouchGFX/generated/gui_generated/src/main_screen \
TouchGFX/generated/gui_generated/src/network_screen \
TouchGFX/generated/images/src \
TouchGFX/generated/images/src/__designer \
TouchGFX/generated/texts/src \
TouchGFX/gui/src/common \
TouchGFX/gui/src/iocontrol_screen \
TouchGFX/gui/src/logger_screen \
TouchGFX/gui/src/main_screen \
TouchGFX/gui/src/model \
TouchGFX/gui/src/network_screen \
TouchGFX/target \

